#mybatis-plus  
mybatis-plus:
    #global-config
    global-config:
        banner: false
        db-config:
          logic-delete-value: -2 #默认值1
          logic-not-delete-value: 0 #默认值0
             #驼峰下划线转换
          table-underline: true
        # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 2
        # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
        field-strategy: 2
        #驼峰下划线转换
        db-column-underline: true
        # 是否动态刷新mapper,开发调试用
        refresh-mapper: true
 #####################configuration：与configLocation:不能同时存在
#    configuration:
       # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
#        cache-enabled: true
        # 延时加载的开关
#        lazyLoadingEnabled: true
        #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
#        call-setters-on-nulls: true
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#        log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
 ######################################################################
    #加载全局的配置文件
    configLocation: classpath:config/mybatis-config.xml
    # 配置mapper的扫描，多个目录用逗号或者分号分隔mapper.xml映射文件   
    mapper-locations: classpath*:/mapper/**/*Mapper.xml
    # 别名包扫描路径，通过该属性可以给包中的类注册别名,多个目录用逗号或者分号分隔
    type-aliases-package: com.wsh.*.domain
    